/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./../components/app-nav.vue')['default']
    CharacterCommon: typeof import('./../components/character/common.vue')['default']
    CharacterLanguage: typeof import('./../components/character/language.vue')['default']
    CharacterLanguages: typeof import('./../components/character/languages.vue')['default']
    CharacterProfession: typeof import('./../components/character/profession.vue')['default']
    CharacterProfessions: typeof import('./../components/character/professions.vue')['default']
    CharacterRelation: typeof import('./../components/character/relation.vue')['default']
    CharacterRelations: typeof import('./../components/character/relations.vue')['default']
    CharacterSelectWithSlider: typeof import('./../components/character/select-with-slider.vue')['default']
    CharacterTest: typeof import('./../components/character/test.vue')['default']
    CharacterTrait: typeof import('./../components/character/trait.vue')['default']
    CharacterTraits: typeof import('./../components/character/traits.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
